using names in artifacts

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -51,6 +51,10 @@ jobs:
           fi
       - name: Install Python Requirements
         run: poetry install -E all
+      - name: Run Formatter
+        run: poetry run black || echo "::warning::Failure ignored!"
+      - name: Run Sort Imports
+        run: poetry run isort || echo "::warning::Failure ignored!"
       - name: Run Linter
         run: poetry run flake8 || echo "::warning::Failure ignored!"
       - name: Run Type Checks
@@ -62,9 +66,10 @@ jobs:
       - name: Build Wheel
         run: poetry build
       - name: Upload Wheel to GitHub Artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3
         with:
-          path: dist/
+          name: dist
+          path: dist
       - name: Upload Coverage
         uses: codecov/codecov-action@v2
 
@@ -102,9 +107,10 @@ jobs:
       - name: Build Docs
         run: poetry run mkdocs build
       - name: Upload Docs to GitHub Artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3
         with:
-          path: site/
+          name: site
+          path: site
 
   deploy:
     name: Deploy
@@ -120,14 +126,8 @@ jobs:
         uses: actions/setup-python@v3
         with:
           python-version: 3.8
-      - name: Get Dist Artifact
-        uses: actions/download-artifact@v2
-        with:
-          path: dist
-      - name: Get Docs Artifact
-        uses: actions/download-artifact@v2
-        with:
-          path: site
+      - name: Get All Artifacts
+        uses: actions/download-artifact@v3
       - name: Install Poetry
         run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
@@ -145,5 +145,4 @@ jobs:
         env:
           PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
         run: |
-          poetry config pypi-token.pypi $PYPI_TOKEN
-          poetry publish
+          poetry publish -u __token__ -p $PYPI_TOKEN
